
language: node_js
bundler_args: --retry 3

# test on only one node.js version: 0.10
node_js:
  - 0.10
before_script:
  - "export DISPLAY=:99.0" 
  - "sh -e /etc/init.d/xvfb start"
  - npm install connect
  - npm install serve-static
  - node -v
  - node server/server.js &
  - sleep 2
script: phantomjs test/qunit/run-qunit.js "http://127.0.0.1:3000/test.html"
