
language: node_js
bundler_args: --retry 3

# test on only one node.js version: 0.8
node_js:
  - 0.8
before_script:
  - "export DISPLAY=:99.0" 
  - "sh -e /etc/init.d/xvfb start"
  - npm install connect
  - node server/server.js &
  - sleep 15

script: phantomjs test/qunit/run-qunit.js "http://127.0.0.1:3000/test.html"
